import org.gradle.api.tasks.testing.logging.TestExceptionFormat

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

group = "simples"

val kotestVersion by extra("4.1.1")
val junit5Version by extra("5.4.0")

plugins {
    id("org.jetbrains.kotlin.jvm").version("1.3.70")
    id("com.github.johnrengelman.shadow").version("4.0.4")

    // Support for building a CLI application.
    application
}

repositories {
    jcenter()

    maven {
        url = uri("https://dl.bintray.com/kotlin/kotlinx")
    }
}

dependencies {
    //Core libs
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    testImplementation("io.kotest:kotest-runner-junit5-jvm:$kotestVersion")
    testImplementation("io.kotest:kotest-runner-console-jvm:$kotestVersion")
    testImplementation("io.kotest:kotest-assertions-core-jvm:$kotestVersion")
}

application {
    // Define the main class for the application.
    mainClassName = "MainKt"
}

tasks.compileKotlin {
    sourceCompatibility = "1.8"
    targetCompatibility = "1.8"

    kotlinOptions {
        jvmTarget = "1.8"
    }
}

tasks.compileTestKotlin {
    sourceCompatibility = "1.8"
    targetCompatibility = "1.8"

    kotlinOptions {
        jvmTarget = "1.8"
    }
}

tasks.test {
    useJUnitPlatform()
    testLogging {
        outputs.upToDateWhen { false } //always run tests
        events("passed", "skipped", "failed")
        showStandardStreams = true
        exceptionFormat = TestExceptionFormat.FULL
    }
}

tasks.shadowJar {
    getArchiveClassifier().set("all")
}

